<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
    <line>
      <![CDATA[The user has failed to login, the page the user currently is]]>
    </line>
  </reporter-output>
  <suite name="Suite" duration-ms="13286" started-at="2016-01-16T15:32:01Z" finished-at="2016-01-16T15:32:14Z">
    <groups>
      <group name="SmokeTest">
        <method signature="Login_Scenario.valid_login(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:sceanrios_TCs.Login_Scenario@18486a3]" name="valid_login" class="sceanrios_TCs.Login_Scenario"/>
      </group> <!-- SmokeTest -->
    </groups>
    <test name="chromeTest" duration-ms="13286" started-at="2016-01-16T15:32:01Z" finished-at="2016-01-16T15:32:14Z">
      <class name="sceanrios_TCs.Login_Scenario">
        <test-method status="PASS" signature="Initialize_browser(java.lang.String)[pri:0, instance:sceanrios_TCs.Login_Scenario@18486a3]" name="Initialize_browser" is-config="true" duration-ms="7452" started-at="2016-01-16T21:02:02Z" finished-at="2016-01-16T21:02:09Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Initialize_browser -->
        <test-method status="FAIL" signature="valid_login(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:sceanrios_TCs.Login_Scenario@18486a3]" name="valid_login" duration-ms="4608" started-at="2016-01-16T21:02:09Z" data-provider="DP_valid_login" finished-at="2016-01-16T21:02:14Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[GB_07]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[1.0]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[qtpworld2008@gmail.com]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[learn123]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[qtpworld2008]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	hola macha,
	The actual found isqtpworld2008 g The expected is qtpworld2008 expected [qtpworld2008] but found [qtpworld2008 g]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	hola macha,
	The actual found isqtpworld2008 g The expected is qtpworld2008 expected [qtpworld2008] but found [qtpworld2008 g]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at sceanrios_TCs.Login_Scenario.valid_login(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[The user has failed to login, the page the user currently is]]>
            </line>
          </reporter-output>
        </test-method> <!-- valid_login -->
        <test-method status="PASS" signature="tear_down()[pri:0, instance:sceanrios_TCs.Login_Scenario@18486a3]" name="tear_down" is-config="true" duration-ms="406" started-at="2016-01-16T21:02:14Z" finished-at="2016-01-16T21:02:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tear_down -->
      </class> <!-- sceanrios_TCs.Login_Scenario -->
    </test> <!-- chromeTest -->
  </suite> <!-- Suite -->
</testng-results>
